// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbot0H8OqthNkra_-CuFQQbUO3VVUsb60',
    appId: '1:619535210439:web:beca8814f494081a6babe2',
    messagingSenderId: '619535210439',
    projectId: 'alapontalk',
    authDomain: 'alapontalk.firebaseapp.com',
    storageBucket: 'alapontalk.appspot.com',
    measurementId: 'G-F90661G2CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARC-63Z8xmGu2LBwcPcfhkoJ3dawNm5pU',
    appId: '1:619535210439:android:25719fd42fa024466babe2',
    messagingSenderId: '619535210439',
    projectId: 'alapontalk',
    storageBucket: 'alapontalk.appspot.com',
  );
}
